version: '3.5'

services:
  nginx:
    image: nginx:latest
    depends_on:
      - app
      - node
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/app:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      context: ../
      dockerfile: website/Dockerfile
    command: ["php-fpm"]
    working_dir: /var/www/app
    volumes:
      - ../website/:/var/www/app
      - ../content/:/var/www/app/storage/app/content

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=website
      - MYSQL_USER=website
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - TZ=UTC
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_polish_ci
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  node:
    image: node:14-slim
    tty: true
    working_dir: /app
    volumes:
      - .:/app
    command: ["node"]

volumes:
  content:
  mysql_data: